/*
r13t API

r13t external API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package r13tExtApi

import (
	"encoding/json"
)

// TLSSecretMetadata struct for TLSSecretMetadata
type TLSSecretMetadata struct {
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NewTLSSecretMetadata instantiates a new TLSSecretMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTLSSecretMetadata() *TLSSecretMetadata {
	this := TLSSecretMetadata{}
	return &this
}

// NewTLSSecretMetadataWithDefaults instantiates a new TLSSecretMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTLSSecretMetadataWithDefaults() *TLSSecretMetadata {
	this := TLSSecretMetadata{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TLSSecretMetadata) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TLSSecretMetadata) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TLSSecretMetadata) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TLSSecretMetadata) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *TLSSecretMetadata) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TLSSecretMetadata) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *TLSSecretMetadata) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *TLSSecretMetadata) SetNamespace(v string) {
	o.Namespace = &v
}

func (o TLSSecretMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	return json.Marshal(toSerialize)
}

type NullableTLSSecretMetadata struct {
	value *TLSSecretMetadata
	isSet bool
}

func (v NullableTLSSecretMetadata) Get() *TLSSecretMetadata {
	return v.value
}

func (v *NullableTLSSecretMetadata) Set(val *TLSSecretMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableTLSSecretMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableTLSSecretMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTLSSecretMetadata(val *TLSSecretMetadata) *NullableTLSSecretMetadata {
	return &NullableTLSSecretMetadata{value: val, isSet: true}
}

func (v NullableTLSSecretMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTLSSecretMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


