/*
r13t API

r13t external API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CertificateData struct for CertificateData
type CertificateData struct {
	TlsCrt *string `json:"tls.crt,omitempty"`
	TlsKey *string `json:"tls.key,omitempty"`
}

// NewCertificateData instantiates a new CertificateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateData() *CertificateData {
	this := CertificateData{}
	return &this
}

// NewCertificateDataWithDefaults instantiates a new CertificateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateDataWithDefaults() *CertificateData {
	this := CertificateData{}
	return &this
}

// GetTlsCrt returns the TlsCrt field value if set, zero value otherwise.
func (o *CertificateData) GetTlsCrt() string {
	if o == nil || o.TlsCrt == nil {
		var ret string
		return ret
	}
	return *o.TlsCrt
}

// GetTlsCrtOk returns a tuple with the TlsCrt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateData) GetTlsCrtOk() (*string, bool) {
	if o == nil || o.TlsCrt == nil {
		return nil, false
	}
	return o.TlsCrt, true
}

// HasTlsCrt returns a boolean if a field has been set.
func (o *CertificateData) HasTlsCrt() bool {
	if o != nil && o.TlsCrt != nil {
		return true
	}

	return false
}

// SetTlsCrt gets a reference to the given string and assigns it to the TlsCrt field.
func (o *CertificateData) SetTlsCrt(v string) {
	o.TlsCrt = &v
}

// GetTlsKey returns the TlsKey field value if set, zero value otherwise.
func (o *CertificateData) GetTlsKey() string {
	if o == nil || o.TlsKey == nil {
		var ret string
		return ret
	}
	return *o.TlsKey
}

// GetTlsKeyOk returns a tuple with the TlsKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateData) GetTlsKeyOk() (*string, bool) {
	if o == nil || o.TlsKey == nil {
		return nil, false
	}
	return o.TlsKey, true
}

// HasTlsKey returns a boolean if a field has been set.
func (o *CertificateData) HasTlsKey() bool {
	if o != nil && o.TlsKey != nil {
		return true
	}

	return false
}

// SetTlsKey gets a reference to the given string and assigns it to the TlsKey field.
func (o *CertificateData) SetTlsKey(v string) {
	o.TlsKey = &v
}

func (o CertificateData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TlsCrt != nil {
		toSerialize["tls.crt"] = o.TlsCrt
	}
	if o.TlsKey != nil {
		toSerialize["tls.key"] = o.TlsKey
	}
	return json.Marshal(toSerialize)
}

type NullableCertificateData struct {
	value *CertificateData
	isSet bool
}

func (v NullableCertificateData) Get() *CertificateData {
	return v.value
}

func (v *NullableCertificateData) Set(val *CertificateData) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateData) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateData(val *CertificateData) *NullableCertificateData {
	return &NullableCertificateData{value: val, isSet: true}
}

func (v NullableCertificateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


