openapi: 3.0.1
info:
  description: r13t external API.
  title: r13t API
  version: 1.0.0
servers:
- url: /
tags:
- description: API version 1
  name: API group
paths:
  /:
    get:
      operationId: Index
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
      summary: Homepage response
  /api/v1/certificate-secret:
    get:
      operationId: GetCertificateSecret
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TLSSecret'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
      summary: Get latest development domain certificate as Kubernetes secret
      tags:
      - API group
components:
  schemas:
    ErrorResponse:
      properties:
        error:
          example: something wrong
          type: string
      type: object
    TLSSecret:
      example:
        metadata:
          name: name
          namespace: namespace
        apiVersion: apiVersion
        data:
          tls.key: tls.key
          tls.crt: tls.crt
        kind: kind
        type: type
      properties:
        apiVersion:
          type: string
        data:
          $ref: '#/components/schemas/TLSSecret_data'
        kind:
          type: string
        metadata:
          $ref: '#/components/schemas/TLSSecret_metadata'
        type:
          type: string
      type: object
    TLSSecret_data:
      example:
        tls.key: tls.key
        tls.crt: tls.crt
      properties:
        tls.crt:
          type: string
        tls.key:
          type: string
      type: object
    TLSSecret_metadata:
      example:
        name: name
        namespace: namespace
      properties:
        name:
          type: string
        namespace:
          type: string
      type: object
  securitySchemes:
    apiToken:
      in: header
      name: Authorization
      type: apiKey
